const skillsAndInterests = [
  {
    title: `Machinist & Fabricator`,
    content: `TIG welding, turning, milling, CNC operator & programmer. For the last 10 years I have gained a wealth of workshop experience and practical skills. Being involved in the prototype, design, and build stages, means I have an all round knowledge base and skillset which has been useful at all stages of development.  This experience lends to problem solving and communication skills.`,
    url: `skills`,
    thumbnail: `../images/StrangerThings.png`,
    link: `https://www.artem.com/projects/stranger-things-the-first-shadow`,
    alt: `The poster from the West end Theatre production of Stranegr Things: The First Shadow.`,
    pic1: `../images/sciProj_pic1.png`,
    pic1text: `This was the main interactive at an exhibition in Denmark called the Ball Factory.`,
    pic1alt: `A picture of the Ball factory's main interactive in Denmark, made by Science Projects Ltd`,
    pic1link: `https://science-projects.org/projects/the-ball-factory-2/`,
    pic2: `../images/artemPlane.png`,
    pic2text: `Me standing in front of the 1:1 model of the BAE Systems new Tempest combat aircraft recreated by Artem SFX`,
    pic2alt: `Me standing in front of the BAE Systems Tempest combat aircraft 1:1 model.`,
    pic2link: `https://www.artem.com/projects/farnborough-airshow`,
    pic3: `../images/artemPiano.png`,
    pic3text: `A photo of the "Exploding Piano" fabricated for Adele's Vegas show.  The first project I worked on when I started at Artem.`,
    pic3alt: `A picture showing the insides of the "exploding piano" for Adele's Vegas show.`,
    pic3link: `https://www.artem.com/projects/weekends-with-adele`,
  },
  {
    title: `Film & TV`,
    content: `I've watched most horror films available in the UK. I love Sci-fi, and really appreciate hard sci-fi. Battlestar Galactica and The Expanse are personal favorites. My top 3 films of all time would be Alien (1979), The Thing (1982) and Ghost in the Shell (1995).`,
    url: `interests`,
    thumbnail: `../images/GITS.png`,
    link: `https://www.imdb.com/title/tt0113568/`,
    alt: `A still image from the openeing of the 1995 Ghost In the Shell film.`,
    pic1: `../images/Alien.png`,
    pic1text: `The iconic 1979 film Alien, directed by Ridley Scott`,
    pic1alt: `The poster for the 1979 film Alien`,
    pic1link: `https://www.imdb.com/title/tt0078748/`,
    pic2: `https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQb9K2z65-KWzNc7-UdVUM_ZgDBh8V3zXKTlwhqs5zlsgHszjz_-D6IgpG-tCGZZvGLbbU39g`,
    pic2text: `The Thing.  A 1982 masterpiece of paranoia and practical effects.`,
    pic2alt: `The poster for the 1982 film The Thing`,
    pic2link: `https://www.imdb.com/title/tt0084787/`,
    pic3: `https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQIoo6g8YitcJ_XanQFA_CshSPXo4nb9O2hizW1PY6qXKXxUlB0AH0lFSo8hGovrqkW0-Vn3w`,
    pic3text: `The 1995 anime film Ghost in the Shell has had a profound and lasting influence on science fiction and exploration of philosophical ideas about consciousness and identity.`,
    pic3alt: `The poster for the 1995 film Ghost in the Shell`,
    pic3link: `https://www.imdb.com/title/tt0113568/`,
  },
  {
    title: `Books`,
    content: `Sci-fi and Fantasy, Sanderson, Rothfuss, P.F. Hamilton and Pierce Brown. The world building of Pandora's Star by P.F. Hamilton is unmatched.  Sanderson is a force of nature when it comes to writing compelling tomes you can get lost in. However, my favourite would be the Red Rising series by Pierce Brown.`,
    url: `books`,
    thumbnail: `../images/RedRisingBooks.jpg`,
    link: `https://www.goodreads.com/book/show/15839976-red-rising`,
    alt: `A stack books from the Red Rising series`,
    pic1: `../images/RedRising.png`,
    pic1text: `In a dystopian future, Darrow, a Red miner on Mars, discovers he and his people are slaves to the ruling Golds. Deceived about Mars's terraforming, he joins a rebellion, infiltrating a Gold academy to exact revenge on the oppressive system. He must fight for survival and freedom in a brutal, color-coded society`,
    pic1alt: `The book cover of Red Rising by Pierce Brown`,
    pic1link: `https://www.goodreads.com/book/show/15839976-red-rising`,
    pic2: `../images/Mistborn.png`,
    pic2text: `In Brandon Sanderson's Mistborn: The Final Empire, a world of ash and mist is ruled by a tyrannical immortal, the Lord Ruler. A brilliant thief, Kelsier, assembles a crew, including the young skaa thief Vin, to overthrow him using Allomancy, a magic system involving the burning of metals. Vin, initially skeptical, trains to master her powers as they attempt to liberate the oppressed skaa. `,
    pic2alt: `The book cover of Mistbornb by Brandon Sanderson`,
    pic2link: `https://www.goodreads.com/book/show/68428.Mistborn`,
    pic3: `../images/PandorasStar.png`,
    pic3text: `In Peter F. Hamilton's "Pandora's Star," humanity has spread across the stars, encountering various alien races. A mysterious anomaly threatens the Commonwealth, leading to a multi-faceted investigation and a quest to understand its nature. The story explores themes of interstellar politics, advanced technology, and first contact, unfolding across a vast, detailed universe.`,
    pic3alt: `The book cover of Pandora's Star by Peter F. Hamilton`,
    pic3link: `https://www.goodreads.com/book/show/45252.Pandora_s_Star?from_search=true&from_srp=true&qid=nBHJkTziap&rank=1`,
  },
  {
    title: `Board Games`,
    content: `I have a core group of friend with whome I play board games with regularly.  One of which has an encyclopedic knowledge of them, and who's colleciton would put board game cafes to shame.  We have spent countless days playing games together over the years.  What used to be after school turned into after work, and we still manage to find time to meet up despite busy working adult schedules.`,
    url: `boardgames`,
    thumbnail: `../images/TI5E-close.jpg`,
    link: `https://en.wikipedia.org/wiki/Twilight_Imperium`,
    alt: `A photo of one of my weekend board game sessions, featuring Twilight Imperium`,
    pic1: `../images/TI5E.jpg`,
    pic1text: `Twilight Imperium is a grand strategy board game of galactic conquest for 3-8 players. Players take on the roles of unique spacefaring civilizations, vying for control of the galaxy through warfare, diplomacy, and trade. Each game features a randomly generated galaxy and a variety of objectives, leading to a unique and epic experience. `,
    pic1alt: `A photo of the table from a day playing Twilight Imperium.`,
    pic1link: `https://en.wikipedia.org/wiki/Twilight_Imperium`,
    pic2: `../images/LOWD.jpg`,
    pic2text: `Lords of Waterdeep is a worker placement board game where players secretly control masked Lords ruling the city of Waterdeep, competing to gain influence by completing quests and expanding the city. Players use agents to recruit adventurers (fighters, rogues, wizards, and clerics) to fulfill quests for rewards and victory points. The game involves strategic placement of agents to gather resources, play intrigue cards, and build new structures to bolster their influence. `,
    pic2alt: `A photo of the table from an evening playing Lords of Waterdeep.`,
    pic2link: `https://en.wikipedia.org/wiki/Lords_of_Waterdeep`,
    pic3: `../images/KingsDilemma.jpg`,
    pic3text: `In "The King's Dilemma," players are council members of a kingdom, tasked with resolving various issues presented as dilemmas. Each decision impacts the kingdom's resources, political standing, and the game's narrative, while also affecting the power and prestige of the players' houses. The game spans multiple sessions, with choices shaping a branching storyline and leading to various possible outcomes and endings. `,
    pic3alt: `A photo of the table from an evening playing The King's Dilemma.`,
    pic3link: `https://boardgamegeek.com/boardgame/245655/the-kings-dilemma`,
  },
];

export default skillsAndInterests;
